In [ ]:
#Aim : To Create 1D , 2D and Multidimensional Array

In [ ]:
#Name : Prashansha Rajendra Sahastrabuddhe
#Roll No : 54
#Sec : A
#Subject : ET-1
#Data : 19/08/2025

In [1]:
# importing the basic library 
import numpy as np

In [3]:
# creating 1D Array using numpy

In [4]:
a1=np.array([10,20,30,40,50])

In [5]:
a1

array([10, 20, 30, 40, 50])

In [6]:
# creating the 2D Array using the numpy

In [7]:
a2=np.array([[10,20,30,40],[60,70,80,90]])

In [8]:
a2

array([[10, 20, 30, 40],
       [60, 70, 80, 90]])

In [9]:
#creating 2D Array using Matrix

In [11]:
a3=np.matrix('11 22;33 44;55 66')
print(a3)

[[11 22]
 [33 44]
 [55 66]]
